name: deploy-app

on:
  pull_request: 
    types: [opened, synchronize]
    branches:
      - main
  push: 
    branches:
      - main
jobs:
  print-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print Message
        run: echo "Deploying app…" 
